- name: Set JBoss EAP Download Facts
  set_fact:
    jboss_eap_artifact_url: "{{ jboss_eap_artifact_source }}"
    jboss_eap_artifact_dl_dest: "{{ jboss_eap_artifacts_dl_dest_dir }}/{{ jboss_eap_artifact_name }}"

- name: Set JBoss EAP Service Directories Facts
  set_fact:
    jboss_eap_home: "{{ jboss_eap_library_dest_dir }}/{{ jboss_eap_home_dir_name }}"

- name: Create JBoss EAP Group
  group:
    name: "{{ jboss_eap_group }}"
    system: yes
    state: present
    gid: "400"

- name: Create JBoss EAP User
  user:
    name: "{{ jboss_eap_user }}"
    comment: "JBoss EAP User"
    uid: "400"
    group: "{{ jboss_eap_group }}"
    home: "{{ jboss_eap_library_dest_dir }}"
    shell: "/bin/bash"

- name: Check Existence of Libraries
  become: true
  stat:
    path: "{{ jboss_eap_library_dest_dir + '/' + jboss_eap_home_dir_name + '/version.txt'}}"
  register: jboss_eap_exists

- name: Get JBOSS source
  get_url:
    url : "{{ s3_eap }}"
    dest: /tmp/
    
- name: Get JDBC driver 
  get_url:
    url :  "{{ s3_jdbc }}"
    dest: /tmp/        

- name: Extract JBoss EAP Libraries
  become: true
  unarchive:
    src: "{{ jboss_eap_artifact_dl_dest }}"
    dest: "{{ jboss_eap_library_dest_dir }}"
    creates: "{{ jboss_eap_home_dir_name }}"
    copy: no
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"
  when: jboss_eap_exists.stat.exists == false

- name: Patch
  include_tasks: apply_patch.yml
  when: jboss_eap_apply_patch|bool

- name: Check if Backup Standalone Directory Exists
  stat:
    path: "{{ jboss_eap_home }}/{{ jboss_eap_standalone_backup_dir_name }}"
  register: standalone_backup_dir

- name: Create Backup Standalone Directory
  command: "cp -r {{ jboss_eap_home }}/{{ jboss_eap_default_mode }} {{ jboss_eap_home }}/{{ jboss_eap_standalone_backup_dir_name }}"
  when: not standalone_backup_dir.stat.exists

- name: Change Permissions on Standalone Backup Directory
  file:
    state: directory
    recurse: yes
    path: "{{ jboss_eap_home }}/{{ jboss_eap_standalone_backup_dir_name }}"
    owner: "{{ jboss_eap_user }}"
    group: "{{ jboss_eap_group }}"

- name: Validate Instance Configuration
  fail:
    msg: Invalid JBoss instance configuration
  when: jboss_instances is undefined or jboss_instances|length == 0

- name: Configure Instances
  include_tasks: eap_jboss_instance.yml
  with_items: "{{ jboss_instances }}"
  loop_control:
    loop_var: instance
